// <auto-generated />
using System;
using ControlOverWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ControlOverWeb.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20251027135927_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ControlOverWeb.Models.Cihaz", b =>
                {
                    b.Property<int>("CihazID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CihazID"));

                    b.Property<string>("CihazAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CihazToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SonGorulme")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CihazID");

                    b.ToTable("Cihazlar");
                });

            modelBuilder.Entity("ControlOverWeb.Models.KomutKuyrugu", b =>
                {
                    b.Property<long>("KomutID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("KomutID"));

                    b.Property<int>("CihazID")
                        .HasColumnType("integer");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("IslemeAlmaZamani")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KomutIcerigi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OlusturmaZamani")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("TamamlanmaZamani")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("KomutID");

                    b.HasIndex("CihazID");

                    b.ToTable("KomutKuyrugu");
                });

            modelBuilder.Entity("ControlOverWeb.Models.KomutKuyrugu", b =>
                {
                    b.HasOne("ControlOverWeb.Models.Cihaz", "Cihaz")
                        .WithMany("Komutlar")
                        .HasForeignKey("CihazID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cihaz");
                });

            modelBuilder.Entity("ControlOverWeb.Models.Cihaz", b =>
                {
                    b.Navigation("Komutlar");
                });
#pragma warning restore 612, 618
        }
    }
}
